name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Check system before
        run: pwd && ls -la

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: glials/rails-compose
          path: rails-compose

      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.99.0

      - name: Check Ruby version
        run: ruby -v

      - name: Check system after
        run: ls -la
